//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeportariBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deportati
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deportati()
        {
            this.DetaliiConfiscari = new HashSet<DetaliiConfiscari>();
            this.DetaliiDeportare = new HashSet<DetaliiDeportare>();
        }
    
        public int Id { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public System.DateTime DATA_NASTERII { get; set; }
        public Nullable<System.DateTime> DATA_DECES { get; set; }
        public int ID_LOCALITATE_RESEDINTA { get; set; }
    
        public virtual Localitati Localitati { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetaliiConfiscari> DetaliiConfiscari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetaliiDeportare> DetaliiDeportare { get; set; }
    }
}
