//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeportariBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetaliiConfiscari
    {
        public int ID_DEPORTAT { get; set; }
        public int ID_OBIECT { get; set; }
        public int CANTITATE { get; set; }
    
        public virtual Deportati Deportati { get; set; }
        public virtual Obiecte Obiecte { get; set; }
    }
}
