//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeportariBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localitati
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Localitati()
        {
            this.Deportati = new HashSet<Deportati>();
            this.DetaliiDeportare = new HashSet<DetaliiDeportare>();
            this.DetaliiDeportare1 = new HashSet<DetaliiDeportare>();
        }
    
        public int ID_LOCALITATE { get; set; }
        public string DENUMIRE { get; set; }
        public int ID_REPUBLICA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deportati> Deportati { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetaliiDeportare> DetaliiDeportare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetaliiDeportare> DetaliiDeportare1 { get; set; }
        public virtual Republici Republici { get; set; }
    }
}
