//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeportariBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BazaDateEntities : DbContext
    {
        public BazaDateEntities()
            : base("name=BazaDateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Deportati> Deportati { get; set; }
        public virtual DbSet<Localitati> Localitati { get; set; }
        public virtual DbSet<Obiecte> Obiecte { get; set; }
        public virtual DbSet<Republici> Republici { get; set; }
        public virtual DbSet<DetaliiConfiscari> DetaliiConfiscari { get; set; }
        public virtual DbSet<DetaliiDeportare> DetaliiDeportare { get; set; }
    }
}
